export const ALL_CHIPS = [
  "Pronoms iel", "TDAH", "Cerveau atypique", "Signes autisme féminin",
  "Fatigue cognitive", "Handicap invisible témoignage", "Validisme systémique",
  "Hypersensibilité sensorielle", "Inclusion scolaire", "Burn-out militant",
  "Auto-diagnostic légitimité", "Handiparentalité", "Neuro-affirmation",
  "Troubles DYS explications", "Décompensation psychique",
  "Culture du consentement", "Charge mentale couple", "Féminicide France",
  "Violence obstétricale", "Précarité menstruelle solutions",
  "Intersectionnalité définition", "Cyber-harcèlement sexiste",
  "Lutte contre la grossophobie", "Injonction à la beauté",
  "Sexisme ordinaire au travail", "Éducation non-sexiste",
  "Patriarcat systémique", "Invisibilisation des femmes",
  "Écoféminisme radical", "Taxe rose",
  "Identité non-binaire", "Transition de genre", "Queer-friendly lieux",
  "Histoire de la communauté LGBT", "Parentalité queer", "Cis-normativité",
  "Déconstruction du genre", "Outing conséquences", "Asexualité spectre",
  "Santé mentale LGBT", "Transphobie ordinaire", "Polyamour éthique",
  "Queer art militant", "Mois des fiertés origine", "Genre fluide",
  "Drag King", "Safe space collectif", "Allié.e définition",
  "Privilège blanc", "Racisme systémique définition",
  "Appropriation culturelle vs échange", "Colorisme témoignages",
  "Violences policières quartiers", "Gentrification conséquences",
  "Justice environnementale", "Laïcité inclusive", "Islamophobie en France",
  "Anti-racisme politique", "Profilage racial", "Droit du sol",
  "Inégalités sociales de santé", "SDF dignité", "Exploitation moderne",
  "Lanceur d'alerte protection", "Minorités visibles",
  "Antispécisme politique", "Mode éthique et durable", "Vegan par étape",
  "Souffrance animale abattoirs", "Éco-anxiété comment gérer",
  "Sobriété numérique", "Agriculture paysanne", "Fast-fashion désastre",
  "Justice intergénérationnelle", "Utopie sociale", "Réduction des risques",
  "Droit à la déconnexion", "Consommation responsable", "Économie circulaire",
  "Protection de la biodiversité", "Énergie citoyenne",
  "Lutte contre le gaspillage", "Bioéthique et justice", "Engagement citoyen",
  "ACAB", "Gilets jaunes bilan", "Grève générale",
  "Logement étudiant crise", "Précarité étudiante", "Kylian Mbappé société",
  "Bigflo et Oli", "Christine and the Queens", "le bac philo",
  "Intelligence artificielle emploi", "Désinformation réseaux sociaux",
  "Liberté de la presse", "Réforme des retraites", "Droit à l'avortement",
  // ... 所有100个词
];