export const ALL_CHIPS = [
  // A1-A2 : mots simples, concrets, du quotidien
  "famille différente",
  "mon amie est handicapée",
  "le sport et les filles",
  "lapin et chat",
  "la nature est belle",
  "Le rose pour les garçons ?",
  "l'école pour tous",
  "être seul.e et heureux.se",
  "j'aime les animaux",
  "les insectes sont beaux",
  "être triste, c'est normal",
  "les sans-abri",
  "ni garçon, ni fille : juste moi",
  "parler avec les mains",
  "écouter ses émotions",
  "un fauteuil roulant en ville",
  "travailler ensemble",
  "mon ami mange vegan",
  "être différent",
  "trop d'écrans !",
  "papa fait la cuisine",
  "le préservatif, c'est la base",
  "aider les autres",
  "les droits des enfants",
  "trop de messages !",
  "les jouets n'ont pas de genre",
  "les pubs partout",
  "dire 'non', c'est important",
  "pauvre et riche",
  "la planète",
  "les animaux souffrent",
  "on dit 'madame le ministre' ?",
  "parler avec un accent",
  "mon ex était toxique",
  "le racisme",
  "les transports en commun",
  "mon copain est un bébé",
  "Trop de selfies !",
  "une famille arc-en-ciel",
  "métro, boulot, dodo",
  "C'est quoi un 'Bail' ?",
  "le cliché du béret et de la baguette",
  "les fêtes culturelles",

  // B1 : sujets familiers, situations concrètes
  "harcèlement à l'école",
  "les bancs pour les sans-abri",
  "le Franglais c'est moche ?",
  "c'est quoi une IST ?",
  "le 'Pick Me' girl / mec",
  "être 'Kink' et fier.e",
  "sortir avec un.e autiste",
  "Le 'White People Meal' (repas de blanc)",
  "mon chat est non-binaire ?",
  "le 'cerveau amoureux' (love brain)",
  "Emily in Paris vs la réalité",
  "les robots sont racistes ?",
  "le ghosting en amitié",
  "Pourquoi les Français adorent les mangas ?",
  "c'est quoi la santé mentale ?",
  "les films d'horreur et les insectes",
  "c'est quoi l'âgisme ?",
  "Les algorithmes me connaissent trop",
  "c'est quoi un préjugé ?",
  "le travail des femmes",
  "faire semblant de travailler",
  "pourquoi le masculin l'emporte ?",
  "le prix de la viande",
  "TDAH",
  "mon cerveau est différent",
  "le VIH n'est plus une sentence",
  "le cyber-harcèlement",
  "précarité étudiante",
  "pourquoi les règles sont tabous ?",
  "le droit de vote",
  "les gros mots et la colère",
  "les femmes dans l'histoire",
  "réseaux sociaux et violence",
  "l'anglais partout, c'est nul ?",
  "arrêter de juger le physique",
  "manger végétarien pourquoi",
  "mon coming out à l'école",
  "les jeux vidéo et les clichés",
  "les métiers invisibles",
  "Les clichés sur la nourriture chinoise",
  "fast-fashion problèmes",
  "les médias et la vérité",
  "les animaux en ville",
  "pourquoi la viande est partout ?",
  "droit à l'avortement",
  "pourquoi les règles coûtent cher ?",
  "liberté de la presse",
  "le foie gras : tradition ou torture ?",
  "Kylian Mbappé et la société",
  "Situationship",
  "grève en France",
  "le télétravail : liberté ou prison ?",
  "le tabou des poils",
  "le bac philo",
  "le regard des autres à la piscine",
  "les moustiques ont-ils des droits ?",
  "Christine and the Queens",
  "consommation responsable",
  "le droit d'être déconnecté",
  "protection de la biodiversité",
  "la dictature du bonheur",
  "les 'anti-héros' qu'on adore",
  "le sexisme dans les films",
  "parler de ses tests avant l'amour",
  "gilets jaunes",
  "intelligence artificielle et emploi",
  "pourquoi aimer les chiens et manger les cochons ?",
  "désinformation sur internet",
  "éco-anxiété",
  le mythe du 'self-made man'",

  // B2 : sujets complexes, argumentation
  "privilège blanc",
  "l'écriture inclusive, c'est quoi ?",
  "validisme systémique",
  "le manspreading dans le métro",
  "la 'slat-shaming' médicale",
  "le 'Passing' : être cru pour ce qu'on est",
  "les médicaments pour les femmes",
  "pink-washing pendant la Pride",
  "les mots qu'on ne peut pas traduire",
  "charge mentale couple",
  "L'avocat : le fruit de la discorde",
  "le privilège de l'ignorance",
  "l'amitié est-elle moins importante ?",
  "les algorithmes sont-ils racistes ?",
  "l'industrie du lait et les vaches",
  "féminicide France",
  "le cuir vegan en plastique : une arnaque ?",
  "intersectionnalité",
  "les mots qui font mal",
  "le travail gratuit des clics",
  "gaslighting : quand il dit 'tu es folle' ",
  "pollution sonore et inégalités",
  "identité non-binaire",
  "la double journée des femmes",
  "violences policières",
  "le français colonial",
  "handisplaining",
  "le colorisme dans les cosmétiques",
  "transphobie ordinaire",
  "profilage racial",
  "gentrification",
  "le syndrome de l'imposteur",
  "justice environnementale",
  "fast-fashion désastre",
  "réforme des retraites",
  "islamophobie en France",
  "violence obstétricale",
  "Le MBTI au travail : aide ou danger ?",
  "sobriété numérique",
  "transphobie ordinaire",
  "l'accessibilité des métros parisiens",
  "antispécisme",
  "burn-out parental",
  "polyamour éthique",
  "le 'Aftercare' : prendre soin de l'autre",
  "ACAB",
  "genre fluide",
  "droit du sol",
  "lanceur d'alerte protection",
  "précarité menstruelle",

  // C1-C2 : nuances, abstractions, débats profonds
  "racisme systémique",
  "urbanisme féministe",
  "le colonialisme dans l'assiette",
  "critique de la 'Hustle Culture'",
  "appropriation culturelle vs échange",
  "cis-normativité",
  "éthique du futur",
  "Patriarcat",
  "la thérapie pour tous (accessibilité)",
  "déconstruction de l'amour romantique",
  "déconstruction du genre",
  "dé-genrer la langue française",
  "patriarcat systémique",
  "écoféminisme radical",
  "le trauma intergénérationnel",
  "invisibilisation des femmes en sciences",
  "bioéthique et justice",
  "pauvreté temporelle",
  "justice intergénérationnelle",
  "auto-diagnostic légitimité",
  "décompensation psychique",
  "l'intersectionnalité : du sexisme à l'antispécisme",
  "neuro-affirmation",
  "hétéropatriarcat et culture mème",
  "handiparentalité",
  "Relation platoniques queer",
  "la glottophobie (accent et classe)",
  "burn-out militant",
  "Handiparentalité",
  "utopie sociale",
  "méritocratie du corps",
  "neuro-queer",
  "réduction des risques drogues",
  "FALC accessibilité",
  "l'anarchie relationnelle",
  "queer art militant",
  "exploitation moderne",
  "engagement citoyen radical",
];