export const ALL_CHIPS = [
  // A1-A2 : mots simples, concrets, du quotidien
  "famille différente",
  "mon amie est handicapée",
  "le sport et les filles",
  "manger sans viande",
  "la nature est belle",
  "l'école pour tous",
  "les sans-abri",
  "travailler ensemble",
  "être différent",
  "aider les autres",
  "les droits des enfants",
  "pauvre et riche",
  "la planète",
  "les animaux souffrent",
  "le racisme",
  "les transports en commun",
  "une famille arc-en-ciel",
  "les fêtes culturelles",

  // B1 : sujets familiers, situations concrètes
  "harcèlement à l'école",
  "inégalités femmes hommes",
  "logement étudiant",
  "le travail des femmes",
  "précarité étudiante",
  "le droit de vote",
  "réseaux sociaux et violence",
  "manger végétarien pourquoi",
  "fast-fashion problèmes",
  "les médias et la vérité",
  "les animaux en ville",
  "droit à l'avortement",
  "liberté de la presse",
  "Kylian Mbappé et la société",
  "grève en France",
  "le bac philo",
  "bigflo et Oli",
  "Christine and the Queens",
  "consommation responsable",
  "protection de la biodiversité",
  "gilets jaunes",
  "intelligence artificielle et emploi",
  "désinformation sur internet",
  "éco-anxiété",

  // B2 : sujets complexes, argumentation
  "privilège blanc",
  "validisme systémique",
  "charge mentale couple",
  "féminicide France",
  "intersectionnalité",
  "identité non-binaire",
  "violences policières",
  "transphobie ordinaire",
  "profilage racial",
  "gentrification",
  "justice environnementale",
  "fast-fashion désastre",
  "réforme des retraites",
  "islamophobie en France",
  "violence obstétricale",
  "sobriété numérique",
  "transphobie ordinaire",
  "antispécisme",
  "polyamour éthique",
  "ACAB",
  "genre fluide",
  "droit du sol",
  "lanceur d'alerte protection",
  "précarité menstruelle",

  // C1-C2 : nuances, abstractions, débats profonds
  "racisme systémique",
  "appropriation culturelle vs échange",
  "cis-normativité",
  "Patriarcat",
  "déconstruction du genre",
  "patriarcat systémique",
  "écoféminisme radical",
  "invisibilisation des femmes en sciences",
  "bioéthique et justice",
  "justice intergénérationnelle",
  "auto-diagnostic légitimité",
  "décompensation psychique",
  "neuro-affirmation",
  "handiparentalité",
  "Relation platoniques queer",
  "burn-out militant",
  "Handiparentalité",
  "utopie sociale",
  "réduction des risques drogues",
  "FALC accessibilité",
  "queer art militant",
  "exploitation moderne",
  "engagement citoyen radical",
];